<a href="https://colab.research.google.com/github/mgrandau/springboard-ml-engineering/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

np.random.seed(1)

def relu(x):
  return (x>0) * x

def relu2deriv(output):
  return output>0

alpha = 0.2
hidden_size = 4

streetlights = np.array([[ 1,0,1],
                         [0,1,1],
                         [0,0,1],
                         [1,1,1]])

walk_vs_stop = np.array([[1,1,0,0]]).T

weights_0_1 = 2*np.random.random((3,hidden_size))-1 
weights_1_2 = 2*np.random.random((hidden_size,1))-1

for iteration in range (60):
  layer_2_error=0
  for i in range(len(streetlights)):
    layer_0 = streetlights[i:i+1]
    layer_1 = relu(np.dot(layer_0, weights_0_1))
    layer_2 = np.dot(layer_1, weights_1_2)
    layer_2_error += np.sum((layer_2-walk_vs_stop[i:i+1])**2)
    layer_2_delta = (walk_vs_stop[i:i+1]-layer_2)
    layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)

    weights_1_2 += alpha* layer_1.T.dot(layer_2_delta)
    weights_0_1 += alpha*layer_0.T.dot(layer_1_delta)

  if(iteration %10 ==9):
    print ("Error:"+ str(layer_2_error))

print(weights_0_1)
print(weights_1_2)
layer_2

Error:0.6342311598444467
Error:0.3583840767631751
Error:0.08301831133032973
Error:0.006467054957103672
Error:0.0003292669000750735
Error:1.5055622665134864e-05
[[-0.16595599  0.91056768 -0.99977125 -0.90023925]
 [-0.70648822 -0.92794391 -0.62747958  0.89703458]
 [-0.20646505 -0.03308324 -0.16161097  0.00237016]]
[[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.11023793]]


array([[0.]])